name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  BUILD:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: "docker build . --file Dockerfile --tag lidorlg/flask-example-new:${{ github.sha }}"
  TEST:
    needs: BUILD
    runs-on: self-hosted
    steps:
    - name: Test the Docker Image
      run: "docker run -itd -p 6969:6969 --name flask lidorlg/flask-example-new:${{ github.sha }}"
    - run: "sleep 5 && curl localhost:6969"
    - run: "docker stop flask && docker rm flask"
  PUSH:
    needs: [BUILD, TEST]
    runs-on: self-hosted
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker Image
      run: "docker push lidorlg/flask-example-new:${{ github.sha }}"
